### ISSUE TITLE
Removing bottom blank space.

### ISSUE THREAD

**Issue by TheBlackVoid** [TheBlackVoid/Portfolio#4]
There is a blank space on the bottom of my [website](https://theblackvoid.github.io/Portfolio/index.html) how do I remove this?

**Comment by ddevereauxx** [comment]
I took a look at this for you. The issue is caused by the size of the image that you're using for the overlay. 

There are a few ways to go about fixing this, but personally, I'd use text inside a div with styling to accomplish the border and try applying your animation to that instead. You should also find the text to be less pixelated if you go this route.
